service: lambda-dr-demo

frameworkVersion: '2'

custom:
  config: ${file(config/${env:DEMOSTAGE}.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  lambdaHashingVersion: 20201221
  environment:
    DEMOSTAGE: ${self:custom.config.stage}

  # iamRoleStatements:
  #   - Effect: Allow
  #     Action:
  #       - codedeploy:*
  #     Resource:
  #       - "*"

functions:
  hello:
    handler: handler.hello
    events:
     - httpApi:
         path: /hello
         method: get
    # deploymentSettings:
    #   type: AllAtOnce
    #   alias: Live
    #   postTrafficHook: postHook

  healthcheck:
    handler: src/hooks/healthCheck.healthCheck
    description: Simple healthcheck to test rollback
    events:
     - httpApi:
         path: /healthcheck
         method: get

  # postHook:
  #   handler: src/hooks/rollbackHook.post

# resources:
#   Resources:
#     Route53HealthCheck:
#       Type: "AWS::Route53::HealthCheck"
#       Properties:
#         HealthCheckConfig:
#           Port: "443"
#           Type: "HTTPS"
#           Regions:
#             - us-east-1
#             - us-west-1
#             - us-west-2
#           FullyQualifiedDomainName: "https://bybqlu5q3f.execute-api.us-east-1.amazonaws.com"
#           ResourcePath: "/health"
#         HealthCheckTags:
#           - Key: Name
#             Value: ${self:provider.stage}-${self:service}

package:
  patterns:
    - '!./**'
    - '!node_modules/**'
    - handler.js
    - config/**
    - src/**
  
plugins:
  - serverless-offline
  - serverless-plugin-canary-deployments